"""DNS RPZ adapter — the one real enforcement adapter for beta (goal E).

Postures (adapter.rpz_mode, the adapter's own maximum):
  OFF      compile only, never publishes;
  OBSERVE  publishes to a monitor-only zone file (clearly marked), no
           resolver consumption expected;
  SHADOW   publishes the candidate zone to disk + optional reload, but the
           zone is NOT in the resolver's response chain for policy answers —
           behavior change must be independently impossible;
  ENFORCE  publishes + reloads a resolver-consumed RPZ; every apply is
           verified by querying the configured resolver and expecting
           NXDOMAIN for the exact FQDN.

Safety invariants:
  - EXACT FQDN selectors only: no wildcards, no prefix deny, no IP rules.
    `compile` refuses anything else and `validate` re-refuses it (selector-
    never-broadens is enforced twice, plus scope in the controller);
  - the FQDN must fall inside the adapter's configured authorized_domains —
    the adapter enforces scope INDEPENDENTLY of policy/controller;
  - receipts carry OBSERVED state (file bytes hash / DNS answer), never a
    repetition of intent. A file write alone is not enforcement;
  - fragment/comment charset is closed (domain.sanitize at the emit
    boundary, defense in depth behind ingest canonicalization).
"""
from __future__ import annotations

import hashlib
import ipaddress
import os
import socket
import struct
import subprocess
from pathlib import Path
from typing import Any

from apip.adapters.base import AdapterError
from apip.config.service import AdapterConfig
from apip.domain.sanitize import rpz_comment_safe, validate_fqdn

_MODE_RANK = {"OFF": 0, "OBSERVE": 1, "SHADOW": 2, "ENFORCE": 3}


def _zone_header(zone_name: str, monitor_only: bool) -> list[str]:
    marker = ("; APIP MONITOR-ONLY RPZ (OBSERVE): not consumed for policy answers"
              if monitor_only
              else "; APIP RPZ zone")
    return [
        "; DO NOT EDIT — generated by the APIP controller",
        marker,
        f"$ORIGIN {zone_name}.",
        "$TTL 30",
        "@ IN SOA localhost. hostmaster.localhost. ( 1 30 30 30 60 )",
        "@ IN NS  localhost.",
    ]


class RpzAdapter:
    name = "rpz"

    def __init__(self, config: AdapterConfig):
        self.config = config
        mode = config.rpz_mode.upper()
        if mode not in _MODE_RANK:
            raise AdapterError(f"invalid rpz mode {config.rpz_mode!r}")
        self._mode = mode
        self._zone_dir = Path(config.zone_dir)
        # ENFORCE requires an explicit authorized-domain scope — never
        # authorize-by-omission at the enforcement edge.
        if mode == "ENFORCE" and not config.authorized_domains:
            raise AdapterError(
                "rpz ENFORCE mode requires adapter.authorized_domains "
                "(the adapter never authorizes by omission)")

    # -- posture --------------------------------------------------------------

    def max_mode(self) -> str:
        return self._mode

    def _require_mode(self, needed: str, what: str) -> None:
        if _MODE_RANK[self._mode] < _MODE_RANK[needed]:
            raise AdapterError(
                f"{what} requires adapter mode {needed} (configured {self._mode})")

    # -- scope (defense in depth layer 3) ---------------------------------------

    def _in_adapter_scope(self, fqdn: str) -> bool:
        """The adapter's OWN boundary: a domain is authorized iff it equals
        or is a subdomain of a configured authorized suffix. ENFORCE without
        any configured suffix cannot authorize anything."""
        if not self.config.authorized_domains:
            return False
        v = fqdn.lower().rstrip(".")
        for d in self.config.authorized_domains:
            d = d.lower().rstrip(".")
            if v == d or v.endswith("." + d):
                return True
        return False

    # -- compile ---------------------------------------------------------------

    def compile(self, decision: Any, indicator_value: str,
                indicator_type: str) -> list[dict]:
        """Compile an exact-FQDN RPZ fragment from a decision.

        Beta contract (goal E): fqdn + dns_nxdomain only, dispositions that
        represent an actual bounded action. Anything else compiles to
        nothing — no action, no receipt.
        """
        if indicator_type != "fqdn" or decision.action != "dns_nxdomain":
            return []
        if decision.disposition not in ("SHADOW_ACTION", "AUTO_ENFORCE",
                                        "PROPOSE_OPERATOR_APPROVAL"):
            return []
        # exact FQDN only — wildcards are refused here AND in validate
        if "*" in indicator_value:
            return []
        owner = validate_fqdn(indicator_value)   # closed charset; raises
        if not self._in_adapter_scope(owner):
            raise AdapterError(
                f"target {owner} outside adapter authorized scope "
                f"{sorted(self.config.authorized_domains)}")
        comment = rpz_comment_safe(
            f"{decision.id} {decision.disposition} policy={decision.policy_version}")
        fragment = f"{owner}. IN CNAME . ; {comment}"
        owner_key = f"{owner}."
        bundle_fragments = [fragment]
        bundle_hash = "bundle--" + hashlib.sha256(
            ("\n".join(bundle_fragments)).encode()).hexdigest()[:24]
        return [{
            "adapter": self.name,
            "rule_id": f"owner:{owner}",
            "fragment": fragment,
            "fragment_hash": "frag--" + hashlib.sha256(
                fragment.encode()).hexdigest()[:24],
            "bundle_id": f"rpz-{self.config.zone_name}",
            "bundle_hash": bundle_hash,
            "selector": {
                "scope_type": "destination_global",
                "destination": owner,
                "exact_fqdn": owner,
            },
        }]

    # -- validate ----------------------------------------------------------------

    def validate(self, candidate: dict) -> dict:
        rule_id = candidate.get("rule_id", "")
        fragment = candidate.get("fragment", "")
        selector = candidate.get("selector") or {}
        if not rule_id.startswith("owner:"):
            raise AdapterError(f"invalid rule id {rule_id!r}")
        owner = rule_id.split("owner:", 1)[1].rstrip(".")
        # selector-never-broadens: the selector must be an exact single FQDN
        # equal to the rule owner. Anything wider (wildcard, network,
        # missing) is refused.
        if selector.get("scope_type") != "destination_global" or not selector.get("exact_fqdn"):
            raise AdapterError("RPZ selector must be destination_global + exact_fqdn")
        if selector["exact_fqdn"].rstrip(".") != owner:
            raise AdapterError("selector does not match rule owner (never broadens)")
        # P1: the destination field must be the SAME single FQDN as the owner —
        # never a wider parent, network, or wildcard. This closes the gap where
        # a selector could carry a broad `destination` while a narrow exact_fqdn
        # slips through the equal-check above.
        if selector.get("destination"):
            if str(selector["destination"]).rstrip(".") != owner:
                raise AdapterError("selector destination does not match rule owner (never broadens)")
        if "*" in owner:
            raise AdapterError("wildcard selectors are not permitted in beta")
        expected = f"{owner}. IN CNAME ."
        if not fragment.startswith(expected):
            raise AdapterError(
                f"fragment does not match the exact-FQDN CNAME . contract: {fragment!r}")
        if not self._in_adapter_scope(owner):
            raise AdapterError(f"owner {owner} outside adapter authorized scope")
        try:
            self._require_mode("SHADOW", "apply")
        except AdapterError:
            # OFF/OBSERVE still allow validate (dry-run), never apply
            pass
        return {"ok": True, "owner": owner, "mode": self._mode}

    # -- apply / verify / revoke ---------------------------------------------------

    def _zone_path(self) -> Path:
        return self._zone_dir / f"{self.config.zone_name}.zone"

    def _read_zone(self) -> str:
        p = self._zone_path()
        if p.is_file():
            return p.read_text(encoding="utf-8")
        return ""

    def _write_zone(self, lines: list[str]) -> str:
        self._zone_dir.mkdir(parents=True, exist_ok=True)
        content = "\n".join(lines) + "\n"
        tmp = self._zone_path().with_suffix(".zone.tmp")
        tmp.write_text(content, encoding="utf-8")
        os.replace(tmp, self._zone_path())
        return content

    def _reload(self) -> dict:
        cmd = self.config.reload_command
        if not cmd:
            return {"reloaded": False, "reason": "no reload_command configured"}
        proc = subprocess.run(cmd, shell=True, capture_output=True, timeout=15)
        if proc.returncode != 0:
            raise AdapterError(
                f"reload command failed rc={proc.returncode}: "
                f"{proc.stderr.decode(errors='replace')[:200]}")
        return {"reloaded": True}

    def apply(self, candidate: dict) -> dict:
        checked = self.validate(candidate)
        owner = checked["owner"]
        self._require_mode("SHADOW", "apply")
        zone = self._read_zone()
        lines = zone.splitlines() if zone else _zone_header(
            self.config.zone_name, monitor_only=(self._mode != "ENFORCE"))
        entry = candidate["fragment"]
        # idempotency: re-applying the same owner replaces the prior line
        entry_key = entry.split(";")[0].strip()
        lines = [l for l in lines if l.split(";")[0].strip() != entry_key]
        lines.append(entry)
        content = self._write_zone(lines)
        reload_info = {"reloaded": False, "reason": "not attempted"}
        reload_error = None
        if self.config.reload_command:
            try:
                reload_info = self._reload()
            except AdapterError as e:
                reload_error = str(e)
        content_hash = hashlib.sha256(content.encode()).hexdigest()
        if reload_error:
            return {"ok": False, "error": f"published but reload failed: {reload_error}"}
        return {
            "ok": True,
            "receipt": {
                "receipt_id": "receipt--" + hashlib.sha256(
                    (candidate["rule_id"] + "\x1f" + content_hash).encode()
                ).hexdigest()[:24],
                "status": "applied",
                "observed": {
                    "zone_file": str(self._zone_path()),
                    "zone_sha256": content_hash,
                    "owner": owner,
                    "reload": reload_info,
                },
            },
        }

    def _dns_query_nxdomain(self, fqdn: str) -> dict:
        """Minimal stdlib DNS A query; returns observed rcode info."""
        server = self.config.verify_query_server
        if not server:
            return {"queried": False, "reason": "no verify_query_server"}
        try:
            addr = ipaddress.ip_address(server)
            server_ip = str(addr)
        except ValueError:
            server_ip = socket.gethostbyname(server)
        qname = fqdn.rstrip(".") + "."
        tid = os.urandom(2)
        flags = 0x0100   # RD
        question = struct.pack(">HH", 1, 1)   # A, IN
        qsection = b"".join(
            bytes([len(label)]) + label.encode() for label in qname.rstrip(".").split(".")) + b"\x00"
        packet = tid + struct.pack(">HHHHH", flags, 1, 0, 0, 0) + qsection + question
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.settimeout(self.config.verify_timeout_s)
        try:
            sock.sendto(packet, (server_ip, self.config.verify_query_port))
            data, _ = sock.recvfrom(4096)
        except (socket.timeout, OSError) as e:
            return {"queried": False, "error": str(e)}
        finally:
            sock.close()
        if len(data) < 12:
            return {"queried": False, "error": "short dns response"}
        rcode = data[3] & 0x0F
        qdcount = struct.unpack(">H", data[4:6])[0]
        ancount = struct.unpack(">H", data[6:8])[0]
        return {"queried": True, "rcode": rcode, "answers": ancount,
                "questions": qdcount}

    def verify(self, candidate: dict) -> dict:
        """INDEPENDENT verification. SHADOW (no resolver consumed): verify =
        the zone file actually contains the exact rule (byte-observed). ENFORCE
        (resolver consumed): additionally query the resolver and require
        NXDOMAIN for the exact FQDN. Never fabricates."""
        owner = candidate.get("selector", {}).get("exact_fqdn", "")
        if not owner:
            owner = candidate.get("rule_id", "").split("owner:", 1)[-1]
        owner = owner.rstrip(".")
        zone = self._read_zone()
        if not zone:
            return {"ok": False, "error": "zone file missing"}
        wanted = f"{owner}. IN CNAME ."
        present = any(l.split(";")[0].strip() == wanted
                      for l in zone.splitlines())
        if not present:
            return {"ok": False, "error": f"rule for {owner} not present in zone"}
        observed: dict[str, Any] = {
            "zone_sha256": hashlib.sha256(zone.encode()).hexdigest(),
            "owner": owner,
            "rule_present": True,
        }
        if self._mode == "ENFORCE" and self.config.verify_query_server:
            dns = self._dns_query_nxdomain(owner)
            observed["dns"] = dns
            if not dns.get("queried"):
                return {"ok": False, "error": "dns verify query failed",
                        "observed": observed}
            if dns.get("rcode") != 3:   # NXDOMAIN
                return {"ok": False, "error": f"resolver did not answer NXDOMAIN",
                        "observed": observed}
        return {"ok": True, "observed": observed}

    def revoke(self, candidate: dict) -> dict:
        """Remove EXACTLY this owner line; verify the zone no longer holds
        it. A missing zone counts as removed (idempotent)."""
        checked = self.validate(candidate)
        owner = checked["owner"]
        zone = self._read_zone()
        if not zone:
            return {"ok": True, "observed": {"removed": owner, "zone_absent": True}}
        wanted = f"{owner}. IN CNAME ."
        lines = [l for l in zone.splitlines() if l.split(";")[0].strip() != wanted]
        if len(lines) == len(zone.splitlines()):
            return {"ok": True, "observed": {"removed": owner, "was_absent": True}}
        content = self._write_zone(lines)
        reload_info = {"reloaded": False, "reason": "not attempted"}
        if self.config.reload_command:
            reload_info = self._reload()
        # independent post-check
        after = self._read_zone()
        still = any(l.split(";")[0].strip() == wanted for l in after.splitlines())
        if still:
            return {"ok": False, "error": "rule still present after revoke"}
        return {"ok": True, "observed": {
            "removed": owner,
            "zone_sha256": hashlib.sha256(after.encode()).hexdigest(),
            "reload": reload_info}}

    def get_state(self, selector: dict) -> dict:
        owner = (selector.get("exact_fqdn") or "").rstrip(".")
        zone = self._read_zone()
        wanted = f"{owner}. IN CNAME ."
        present = bool(owner) and any(
            l.split(";")[0].strip() == wanted for l in zone.splitlines())
        return {"owner": owner, "present": present, "mode": self._mode}

    def health(self) -> dict:
        base = {
            "name": self.name,
            "mode": self._mode,
            "zone": self.config.zone_name,
            "authorized_domains": sorted(self.config.authorized_domains),
            "reload_configured": bool(self.config.reload_command),
        }
        if self._mode == "OFF":
            base["status"] = "ok"
            base["note"] = "adapter OFF: compiles only"
            return base
        zone_path = self._zone_path()
        if zone_path.is_file():
            base["status"] = "ok"
            base["zone_file"] = str(zone_path)
        else:
            base["status"] = "degraded" if self._mode == "ENFORCE" else "ok"
            base["note"] = "zone file not yet created (no applies yet)"
        return base
